/*
 * This source file was generated by the Gradle 'init' task
 */
package com.undercurrent.tests

import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        assert(true) { "This should be true" }
    }
}
